### ISSUE TITLE
npm install 报错了。。。

### ISSUE THREAD

**Issue by L1nY4n** [RodgerLai/nodejs-nedb-excel#1]
C:\Users\ly\Desktop\nodejs-nedb-excel-master>npm install
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\ly\AppData\Local\Temp\npm-10868-02b6314a\registry.npmjs.org\esprima-fb\-\esprima-fb-3001.0001.0000-dev-harmony-fb.tgz
npm ERR! Expected: b77d37abcd38ea0b77426bb8bc2922ce6b426411
npm ERR! Actual:   f786688836761070e16680250d4c4f6997f20b65
npm ERR! From:     https://registry.npmjs.org/esprima-fb/-/esprima-fb-3001.0001.0000-dev-harmony-fb.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ly\Desktop\nodejs-nedb-excel-master\npm-debug.log

**Comment by RodgerLai** [comment]
我重新下载了，我和你一样的node和npm版本，install没问题，这是你npm环境的问题，
