### ISSUE TITLE
npm run prod编译后

### ISSUE THREAD

**Issue by Janegaoo** [RodgerLai/nodejs-nedb-excel#2]
请问，npm run prod编译到dist目录后，怎么能正常运行dist下的index.html,怎么和真是库连接，谢谢！

**Comment by RodgerLai** [comment]
打开http://localhost:3000  数据库是nedb 不用安装配置，轻巧文本即插即用型

**Comment by Janegaoo** [comment]
抱歉，可能我的描述不清楚，其实我是想问，怎么正常运行dist下的index.html这个文件，比如说，本地怎么试运行

**Comment by Janegaoo** [comment]
比如说http://localhost:3000/dist/ 就可以运行了？用什么路径运行呢

**Comment by RodgerLai** [comment]
你可以npm run prod, 在dist生成静态资源。但是有登录限制，你可以尝试去掉登录模块重新npm run prod

**Comment by Janegaoo** [comment]
好的，我试试，非常感谢！

**Comment by RodgerLai** [comment]
在dist生成的静态资源，你可以在本地直接打开index.html, 或者丢在任意一个web服务器里都行

**Comment by Janegaoo** [comment]
谢谢！
