### ISSUE TITLE
npm run dev 访问http://localhost:8080地址 报跨域错误

### ISSUE THREAD

**Issue by Janegaoo** [RodgerLai/nodejs-nedb-excel#3]
请问，npm run dev 访问http://localhost:8080地址 报跨域错误 http://localhost:8080访问不起来吗？
错误如下：
Failed to load http://localhost:3000/api/getCurrentUser: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
Logger.js:178 App: getCurrentUser error, Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at Request.crossDomainError (client.js:702)
    at XMLHttpRequest.xhr.onreadystatechange (client.js:770)

谢谢！

**Comment by RodgerLai** [comment]
请先启动服务端 npm start, 再编译静态资源请npm run dev ，最后访问服务端首页地址http://localhost:3000/

你访问的http://localhost:8080/  是静态资源的地址，如要去除登录拦截请自行去除登录模块

**Comment by Janegaoo** [comment]
好的，谢谢
